"""Complete EPIMS schema — all tables from actual SQLAlchemy models.

Revision ID: 001
Revises:
"""
from __future__ import annotations
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── Sequences ─────────────────────────────────────────────────────────────
    op.execute("CREATE SEQUENCE IF NOT EXISTS seq_pr_number  START 1")
    op.execute("CREATE SEQUENCE IF NOT EXISTS seq_po_number  START 1")
    op.execute("CREATE SEQUENCE IF NOT EXISTS seq_grn_number START 1")
    op.execute("CREATE SEQUENCE IF NOT EXISTS seq_inv_number START 1")
    op.execute("CREATE SEQUENCE IF NOT EXISTS seq_mat_number START 1")
    op.execute("CREATE SEQUENCE IF NOT EXISTS seq_ven_number START 1")
    op.execute("CREATE SEQUENCE IF NOT EXISTS seq_mov_number START 1")

    # ── Auth ──────────────────────────────────────────────────────────────────
    op.create_table("auth_permissions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("resource", sa.String(100), nullable=False),
        sa.Column("action", sa.String(50), nullable=False),
        sa.Column("description", sa.String(255)),
        sa.UniqueConstraint("resource", "action"),
    )
    op.create_table("auth_roles",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(50), unique=True, nullable=False),
        sa.Column("description", sa.String(255)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_table("auth_users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("employee_id", sa.String(20), unique=True, nullable=False),
        sa.Column("email", sa.String(255), unique=True, nullable=False),
        sa.Column("full_name", sa.String(255), nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("is_active", sa.Boolean, default=True, nullable=False),
        sa.Column("is_superuser", sa.Boolean, default=False, nullable=False),
        sa.Column("department", sa.String(100)),
        sa.Column("cost_center", sa.String(20)),
        sa.Column("manager_id", postgresql.UUID(as_uuid=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_table("auth_role_permissions",
        sa.Column("role_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_roles.id", ondelete="CASCADE"), nullable=False),
        sa.Column("permission_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_permissions.id", ondelete="CASCADE"), nullable=False),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table("auth_user_roles",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("role_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_roles.id", ondelete="CASCADE"), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )

    # ── Material Master ───────────────────────────────────────────────────────
    op.create_table("material_groups",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("code", sa.String(20), unique=True, nullable=False),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("description", sa.Text),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_table("units_of_measure",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("code", sa.String(10), unique=True, nullable=False),
        sa.Column("name", sa.String(50), nullable=False),
        sa.Column("base_unit", sa.String(10)),
        sa.Column("conversion_factor", sa.Numeric(18, 6), nullable=False, server_default="1"),
    )
    op.create_table("materials",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("material_number", sa.String(30), unique=True, nullable=False),
        sa.Column("description", sa.String(255), nullable=False),
        sa.Column("material_type", sa.String(30), nullable=False),
        sa.Column("material_group_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("material_groups.id")),
        sa.Column("base_uom_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("units_of_measure.id")),
        sa.Column("purchase_uom_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("units_of_measure.id")),
        sa.Column("valuation_class", sa.String(20)),
        sa.Column("standard_price", sa.Numeric(18, 4)),
        sa.Column("moving_average_price", sa.Numeric(18, 4)),
        sa.Column("price_unit", sa.Numeric(10, 3), server_default="1"),
        sa.Column("currency", sa.String(3), server_default="INR"),
        sa.Column("weight_gross", sa.Numeric(10, 3)),
        sa.Column("weight_net", sa.Numeric(10, 3)),
        sa.Column("weight_unit", sa.String(5)),
        sa.Column("volume", sa.Numeric(10, 3)),
        sa.Column("volume_unit", sa.String(5)),
        sa.Column("storage_conditions", sa.String(100)),
        sa.Column("shelf_life_days", sa.Integer),
        sa.Column("reorder_point", sa.Numeric(18, 3)),
        sa.Column("min_order_qty", sa.Numeric(18, 3)),
        sa.Column("max_order_qty", sa.Numeric(18, 3)),
        sa.Column("lead_time_days", sa.Integer),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("created_by", postgresql.UUID(as_uuid=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )

    # ── Vendor Master ─────────────────────────────────────────────────────────
    op.create_table("vendors",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("vendor_number", sa.String(20), unique=True, nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("short_name", sa.String(50)),
        sa.Column("vendor_type", sa.String(30), nullable=False),
        sa.Column("tax_id", sa.String(50)),
        sa.Column("gst_number", sa.String(20)),
        sa.Column("pan_number", sa.String(20)),
        sa.Column("email", sa.String(255)),
        sa.Column("phone", sa.String(30)),
        sa.Column("website", sa.String(255)),
        sa.Column("payment_terms", sa.String(50), nullable=False, server_default="NET30"),
        sa.Column("payment_method", sa.String(30)),
        sa.Column("bank_name", sa.String(100)),
        sa.Column("bank_account", sa.String(50)),
        sa.Column("bank_ifsc", sa.String(20)),
        sa.Column("credit_limit", sa.Numeric(18, 2)),
        sa.Column("currency", sa.String(3), nullable=False, server_default="INR"),
        sa.Column("status", sa.String(20), nullable=False, server_default="ACTIVE"),
        sa.Column("blocked_reason", sa.Text),
        sa.Column("rating", sa.Numeric(3, 2)),
        sa.Column("created_by", postgresql.UUID(as_uuid=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_table("vendor_addresses",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("vendor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("vendors.id", ondelete="CASCADE"), nullable=False),
        sa.Column("address_type", sa.String(20), nullable=False),
        sa.Column("address_line1", sa.String(255), nullable=False),
        sa.Column("address_line2", sa.String(255)),
        sa.Column("city", sa.String(100), nullable=False),
        sa.Column("state", sa.String(100)),
        sa.Column("pincode", sa.String(10)),
        sa.Column("country", sa.String(3), nullable=False, server_default="IND"),
        sa.Column("is_default", sa.Boolean, nullable=False, server_default="false"),
    )
    op.create_table("vendor_contacts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("vendor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("vendors.id", ondelete="CASCADE"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("designation", sa.String(100)),
        sa.Column("email", sa.String(255)),
        sa.Column("phone", sa.String(30)),
        sa.Column("is_primary", sa.Boolean, nullable=False, server_default="false"),
    )
    op.create_table("vendor_material_info",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("vendor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("vendors.id", ondelete="CASCADE"), nullable=False),
        sa.Column("material_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("materials.id", ondelete="CASCADE"), nullable=False),
        sa.Column("vendor_mat_num", sa.String(50)),
        sa.Column("last_price", sa.Numeric(18, 4)),
        sa.Column("last_currency", sa.String(3)),
        sa.Column("last_po_date", sa.Date),
        sa.Column("lead_time_days", sa.Integer),
        sa.Column("min_order_qty", sa.Numeric(18, 3)),
        sa.UniqueConstraint("vendor_id", "material_id"),
    )

    # ── Warehouse ─────────────────────────────────────────────────────────────
    op.create_table("warehouses",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("code", sa.String(10), unique=True, nullable=False),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("warehouse_type", sa.String(30)),
        sa.Column("address", sa.Text),
        sa.Column("manager_id", postgresql.UUID(as_uuid=True)),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_table("storage_locations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("warehouse_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("warehouses.id", ondelete="CASCADE"), nullable=False),
        sa.Column("code", sa.String(20), nullable=False),
        sa.Column("name", sa.String(100)),
        sa.Column("location_type", sa.String(30)),
        sa.Column("aisle", sa.String(10)),
        sa.Column("rack", sa.String(10)),
        sa.Column("level", sa.String(10)),
        sa.Column("bin", sa.String(10)),
        sa.Column("capacity_weight", sa.Numeric(10, 2)),
        sa.Column("capacity_volume", sa.Numeric(10, 2)),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
    )

    # ── Inventory ─────────────────────────────────────────────────────────────
    op.create_table("inventory_stock",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("material_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("materials.id"), nullable=False),
        sa.Column("warehouse_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("warehouses.id"), nullable=False),
        sa.Column("storage_location_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("storage_locations.id")),
        sa.Column("batch_number", sa.String(50)),
        sa.Column("stock_type", sa.String(30), nullable=False, server_default="UNRESTRICTED"),
        sa.Column("quantity", sa.Numeric(18, 3), nullable=False, server_default="0"),
        sa.Column("uom_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("units_of_measure.id")),
        sa.Column("valuation_price", sa.Numeric(18, 4)),
        sa.Column("currency", sa.String(3), nullable=False, server_default="INR"),
        sa.Column("last_movement_date", sa.Date),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_table("stock_movements",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("movement_number", sa.String(30), unique=True, nullable=False),
        sa.Column("movement_type", sa.String(30), nullable=False),
        sa.Column("movement_date", sa.Date, nullable=False),
        sa.Column("material_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("materials.id"), nullable=False),
        sa.Column("to_warehouse_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("warehouses.id")),
        sa.Column("to_location_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("storage_locations.id")),
        sa.Column("quantity", sa.Numeric(18, 3), nullable=False),
        sa.Column("uom_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("units_of_measure.id")),
        sa.Column("unit_price", sa.Numeric(18, 4)),
        sa.Column("total_value", sa.Numeric(18, 2)),
        sa.Column("currency", sa.String(3), nullable=False, server_default="INR"),
        sa.Column("reference_doc_type", sa.String(30)),
        sa.Column("reference_doc_id", postgresql.UUID(as_uuid=True)),
        sa.Column("batch_number", sa.String(50)),
        sa.Column("reason", sa.Text),
        sa.Column("posted_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )

    # ── Procurement ───────────────────────────────────────────────────────────
    op.create_table("purchase_requisitions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("pr_number", sa.String(20), unique=True, nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("description", sa.Text),
        sa.Column("status", sa.String(30), nullable=False, server_default="DRAFT"),
        sa.Column("priority", sa.String(20), nullable=False, server_default="NORMAL"),
        sa.Column("required_date", sa.Date),
        sa.Column("cost_center", sa.String(20)),
        sa.Column("plant", sa.String(20)),
        sa.Column("warehouse_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("warehouses.id")),
        sa.Column("requested_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id"), nullable=False),
        sa.Column("department", sa.String(100)),
        sa.Column("total_value", sa.Numeric(18, 2), nullable=False, server_default="0"),
        sa.Column("currency", sa.String(3), nullable=False, server_default="INR"),
        sa.Column("notes", sa.Text),
        sa.Column("rejection_reason", sa.Text),
        sa.Column("submitted_at", sa.DateTime(timezone=True)),
        sa.Column("approved_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_table("pr_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("pr_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("purchase_requisitions.id", ondelete="CASCADE"), nullable=False),
        sa.Column("line_number", sa.Integer, nullable=False),
        sa.Column("material_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("materials.id")),
        sa.Column("description", sa.String(255), nullable=False),
        sa.Column("quantity", sa.Numeric(18, 3), nullable=False),
        sa.Column("uom_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("units_of_measure.id")),
        sa.Column("estimated_price", sa.Numeric(18, 4)),
        sa.Column("estimated_value", sa.Numeric(18, 2)),
        sa.Column("currency", sa.String(3), nullable=False, server_default="INR"),
        sa.Column("required_date", sa.Date),
        sa.Column("preferred_vendor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("vendors.id")),
        sa.Column("delivery_address", sa.Text),
        sa.Column("specifications", sa.Text),
        sa.Column("status", sa.String(20), nullable=False, server_default="OPEN"),
    )
    op.create_table("purchase_orders",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("po_number", sa.String(20), unique=True, nullable=False),
        sa.Column("pr_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("purchase_requisitions.id")),
        sa.Column("vendor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("vendors.id"), nullable=False),
        sa.Column("status", sa.String(30), nullable=False, server_default="DRAFT"),
        sa.Column("po_type", sa.String(20), nullable=False, server_default="STANDARD"),
        sa.Column("order_date", sa.Date, nullable=False),
        sa.Column("delivery_date", sa.Date),
        sa.Column("payment_terms", sa.String(50)),
        sa.Column("incoterms", sa.String(20)),
        sa.Column("delivery_address", sa.Text),
        sa.Column("warehouse_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("warehouses.id")),
        sa.Column("currency", sa.String(3), nullable=False, server_default="INR"),
        sa.Column("subtotal", sa.Numeric(18, 2), nullable=False, server_default="0"),
        sa.Column("tax_amount", sa.Numeric(18, 2), nullable=False, server_default="0"),
        sa.Column("discount_amount", sa.Numeric(18, 2), nullable=False, server_default="0"),
        sa.Column("total_amount", sa.Numeric(18, 2), nullable=False, server_default="0"),
        sa.Column("amount_received", sa.Numeric(18, 2), nullable=False, server_default="0"),
        sa.Column("amount_invoiced", sa.Numeric(18, 2), nullable=False, server_default="0"),
        sa.Column("notes", sa.Text),
        sa.Column("internal_notes", sa.Text),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id")),
        sa.Column("approved_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id")),
        sa.Column("released_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_table("po_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("po_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("purchase_orders.id", ondelete="CASCADE"), nullable=False),
        sa.Column("pr_item_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pr_items.id")),
        sa.Column("line_number", sa.Integer, nullable=False),
        sa.Column("material_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("materials.id")),
        sa.Column("description", sa.String(255), nullable=False),
        sa.Column("quantity", sa.Numeric(18, 3), nullable=False),
        sa.Column("uom_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("units_of_measure.id")),
        sa.Column("unit_price", sa.Numeric(18, 4), nullable=False),
        sa.Column("discount_pct", sa.Numeric(5, 2), nullable=False, server_default="0"),
        sa.Column("tax_pct", sa.Numeric(5, 2), nullable=False, server_default="0"),
        sa.Column("net_value", sa.Numeric(18, 2), nullable=False),
        sa.Column("delivery_date", sa.Date),
        sa.Column("qty_received", sa.Numeric(18, 3), nullable=False, server_default="0"),
        sa.Column("qty_invoiced", sa.Numeric(18, 3), nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="OPEN"),
    )
    op.create_table("goods_receipts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("grn_number", sa.String(20), unique=True, nullable=False),
        sa.Column("po_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("purchase_orders.id"), nullable=False),
        sa.Column("vendor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("vendors.id")),
        sa.Column("warehouse_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("warehouses.id"), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="DRAFT"),
        sa.Column("receipt_date", sa.Date, nullable=False),
        sa.Column("delivery_note", sa.String(100)),
        sa.Column("vehicle_number", sa.String(30)),
        sa.Column("driver_name", sa.String(100)),
        sa.Column("total_value", sa.Numeric(18, 2), nullable=False, server_default="0"),
        sa.Column("currency", sa.String(3), nullable=False, server_default="INR"),
        sa.Column("notes", sa.Text),
        sa.Column("posted_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id")),
        sa.Column("posted_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_table("grn_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("grn_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("goods_receipts.id", ondelete="CASCADE"), nullable=False),
        sa.Column("po_item_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("po_items.id")),
        sa.Column("line_number", sa.Integer, nullable=False),
        sa.Column("material_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("materials.id")),
        sa.Column("quantity_delivered", sa.Numeric(18, 3), nullable=False),
        sa.Column("quantity_accepted", sa.Numeric(18, 3), nullable=False),
        sa.Column("quantity_rejected", sa.Numeric(18, 3), nullable=False, server_default="0"),
        sa.Column("uom_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("units_of_measure.id")),
        sa.Column("unit_price", sa.Numeric(18, 4)),
        sa.Column("net_value", sa.Numeric(18, 2)),
        sa.Column("storage_location_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("storage_locations.id")),
        sa.Column("batch_number", sa.String(50)),
        sa.Column("expiry_date", sa.Date),
        sa.Column("inspection_note", sa.Text),
        sa.Column("rejection_reason", sa.Text),
    )

    # ── Invoice / 3-Way Match ─────────────────────────────────────────────────
    op.create_table("invoices",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("invoice_number", sa.String(50), unique=True, nullable=False),
        sa.Column("vendor_invoice_number", sa.String(100)),
        sa.Column("vendor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("vendors.id"), nullable=False),
        sa.Column("po_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("purchase_orders.id")),
        sa.Column("status", sa.String(30), nullable=False, server_default="PENDING_VERIFICATION"),
        sa.Column("invoice_date", sa.Date, nullable=False),
        sa.Column("due_date", sa.Date),
        sa.Column("currency", sa.String(3), nullable=False, server_default="INR"),
        sa.Column("subtotal", sa.Numeric(18, 2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(18, 2), nullable=False, server_default="0"),
        sa.Column("total_amount", sa.Numeric(18, 2), nullable=False),
        sa.Column("paid_amount", sa.Numeric(18, 2), nullable=False, server_default="0"),
        sa.Column("match_status", sa.String(20)),
        sa.Column("tolerance_pct", sa.Numeric(5, 2), nullable=False, server_default="2.0"),
        sa.Column("dispute_reason", sa.Text),
        sa.Column("notes", sa.Text),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id")),
        sa.Column("verified_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id")),
        sa.Column("verified_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_table("invoice_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("invoice_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("invoices.id", ondelete="CASCADE"), nullable=False),
        sa.Column("po_item_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("po_items.id")),
        sa.Column("grn_item_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("grn_items.id")),
        sa.Column("line_number", sa.Integer, nullable=False),
        sa.Column("material_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("materials.id")),
        sa.Column("description", sa.String(255)),
        sa.Column("quantity", sa.Numeric(18, 3), nullable=False),
        sa.Column("unit_price", sa.Numeric(18, 4), nullable=False),
        sa.Column("net_value", sa.Numeric(18, 2), nullable=False),
        sa.Column("match_flag", sa.String(20)),
        sa.Column("variance_pct", sa.Numeric(8, 4)),
    )
    op.create_table("three_way_match_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("invoice_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("invoices.id"), nullable=False, unique=True),
        sa.Column("po_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("purchase_orders.id")),
        sa.Column("grn_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("goods_receipts.id")),
        sa.Column("match_result", sa.String(20), nullable=False),
        sa.Column("price_variance", sa.Numeric(18, 4)),
        sa.Column("qty_variance", sa.Numeric(18, 3)),
        sa.Column("value_variance", sa.Numeric(18, 2)),
        sa.Column("tolerance_pct", sa.Numeric(5, 2)),
        sa.Column("notes", sa.Text),
        sa.Column("checked_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id")),
        sa.Column("checked_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )

    # ── Approvals ─────────────────────────────────────────────────────────────
    op.create_table("approval_workflows",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(100), unique=True, nullable=False),
        sa.Column("document_type", sa.String(30), nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("description", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_table("approval_rules",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("workflow_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("approval_workflows.id", ondelete="CASCADE"), nullable=False),
        sa.Column("step_order", sa.Integer, nullable=False),
        sa.Column("approver_type", sa.String(30), nullable=False),
        sa.Column("approver_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id")),
        sa.Column("approver_role", sa.String(50)),
        sa.Column("min_amount", sa.Numeric(18, 2)),
        sa.Column("max_amount", sa.Numeric(18, 2)),
        sa.Column("department", sa.String(100)),
        sa.Column("is_mandatory", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("timeout_hours", sa.Integer, nullable=False, server_default="48"),
        sa.Column("escalate_to_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id")),
    )
    op.create_table("approval_instances",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("workflow_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("approval_workflows.id"), nullable=False),
        sa.Column("document_type", sa.String(30), nullable=False),
        sa.Column("document_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("current_step", sa.Integer, nullable=False, server_default="1"),
        sa.Column("status", sa.String(20), nullable=False, server_default="PENDING"),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
    )
    op.create_table("approval_actions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("instance_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("approval_instances.id", ondelete="CASCADE"), nullable=False),
        sa.Column("rule_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("approval_rules.id")),
        sa.Column("step_order", sa.Integer, nullable=False),
        sa.Column("approver_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id"), nullable=False),
        sa.Column("action", sa.String(20), nullable=False),
        sa.Column("comments", sa.Text),
        sa.Column("delegated_to_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id")),
        sa.Column("acted_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_table("approval_delegations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("delegator_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id"), nullable=False),
        sa.Column("delegate_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id"), nullable=False),
        sa.Column("document_type", sa.String(30)),
        sa.Column("valid_to", sa.Date, nullable=False),
        sa.Column("reason", sa.Text),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )

    # ── Notifications ─────────────────────────────────────────────────────────
    op.create_table("notification_templates",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("event_type", sa.String(100), unique=True, nullable=False),
        sa.Column("channel", sa.String(20), nullable=False),
        sa.Column("subject", sa.String(255)),
        sa.Column("body_html", sa.Text),
        sa.Column("body_text", sa.Text),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
    )
    op.create_table("notifications",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("recipient_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id"), nullable=False),
        sa.Column("event_type", sa.String(100), nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("message", sa.Text),
        sa.Column("channel", sa.String(20), nullable=False, server_default="IN_APP"),
        sa.Column("reference_type", sa.String(30)),
        sa.Column("reference_id", postgresql.UUID(as_uuid=True)),
        sa.Column("is_read", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("read_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )

    # ── Audit ─────────────────────────────────────────────────────────────────
    op.create_table("audit_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("entity_type", sa.String(50), nullable=False),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("action", sa.String(30), nullable=False),
        sa.Column("old_values", postgresql.JSONB),
        sa.Column("new_values", postgresql.JSONB),
        sa.Column("changed_fields", postgresql.JSONB),
        sa.Column("performed_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("auth_users.id")),
        sa.Column("performed_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("ip_address", sa.String(45)),
        sa.Column("user_agent", sa.Text),
    )
    op.create_index("ix_audit_entity", "audit_logs", ["entity_type", "entity_id"])
    op.create_index("ix_pr_status", "purchase_requisitions", ["status"])
    op.create_index("ix_po_status", "purchase_orders", ["status"])
    op.create_index("ix_inv_status", "invoices", ["status"])


def downgrade() -> None:
    pass
